server:
  port: 8899
  servlet:
    encoding:
      force-response: true



spring:
  redis:
    lettuce:
      pool:
        max-active: 5 # pool에 할당될 수 있는 커넥션 최대수
        max-idle: 5 # pool의 'idle' 커넥션 최대수
        min-idle: 2
    host: localhost
    port: 6379
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/payhere
    username: root
    password: 1234

  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
    database : mysql
    hibernate.ddl-auto : update
    default_batch_fetch_size: 1000
    hibernate.naming.strategy : org.hibernate.cfg.ImprovedNamingStrategy
    hibernate.naming.physical-strategy : org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    generate-ddl : false
    properties.hibernate.format_sql : true
    properties.hibernate.enable_lazy_load_no_trans : true

jwt:
  token:
    secret: payhere.hello.world

